apiVersion: v2
name: openshift-console
description: A Helm chart for Kubernetes

type: application

# This is the chart version.
version: 1.0.2

# This is the version number of the application being deployed.
# https://docs.openshift.com/container-platform/4.18/release_notes/ocp-4-18-release-notes.html
appVersion: "4.16.0"
