{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
  namespace: default
type: Opaque
data:
  clientSecret: {{ .Values.secret.clientSecret }}
{{- end }}