{{- if .Values.secrets.idpSecret.create -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.idpSecret.secretName }}
  namespace: default
type: Opaque
data:
  clientSecret: {{ .Values.secrets.idpSecret.clientSecret }}
{{- end }}