{{- if .Values.serviceAccount.create -}}
{{- if ne .Values.serviceAccount.name "default" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshift-console.serviceAccountName" . }}
  labels:
    {{- include "openshift-console.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}