apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "openshift-console.fullname" . }}-user-settings
  namespace: openshift-console-user-settings
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openshift-console.fullname" . }}-user-settings
  namespace: openshift-console-user-settings
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openshift-console.fullname" . }}-user-settings
subjects:
- kind: ServiceAccount
  name: {{ include "openshift-console.serviceAccountName" . }}
  namespace: openshift-console
